### ISSUE TITLE
Suggestion template is a little broken.

### ISSUE THREAD

**Issue by RDKRACZ** [MultiMC/MultiMC5#3939]
![Screenshot from 2021-07-16 12-42-55](https://user-images.githubusercontent.com/43277609/125936067-b07140a6-fdbf-4b99-8415-abc298c9bd36.png)

There is no editor under "You may use the editor below to elaborate further."
Current code:
```
- type: markdown
  attributes:
    value: |
      ### You may use the editor below to elaborate further.
# The issue_body: true up there makes the standard WYSIWYG editor for issues show up down here.
```
